### ISSUE TITLE
Support for delete action?

### ISSUE THREAD

**Issue by czater** [RxSwiftCommunity/RxRealmDataSources#14]
Hello!
I wonder if you plan do add support for swipe to delete action as it is in RxDataSources tableView.rx.itemDeleted ? It would be great :)

**Comment by icanzilb** [comment]
Not out of the box. You can set `delegate` or `dataSource` which will be used as fallbacks - e.g. you can set your VC as delegate of your rxrealmdatasource and it will automatically forward any standard table view delegate calls to your VC - then you can implement methods as normal if that works for you

**Comment by czater** [comment]
well ok, it works :)
