### ISSUE TITLE
Releasing 2.10.0

### ISSUE THREAD

**Issue by icanzilb** [RxSwiftCommunity/RxRealmDataSources#25]
@freak4pc could you find 10 minutes to try pushing 2.10.0 to CocoaPods? I've been trying and re-trying over the last 2 days but the latest stable CocoaPods fails with `block in validate_delegate': #<Pod::UserInterface::InspectorReporter:0x007fdcbc738408> does not handle inspector_successfully_recieved_report (RuntimeError)` which I can't seem to fix.

**Comment by freak4pc** [comment]
Done !

🎉  Congrats

 🚀  RxRealmDataSources (0.2.10) successfully published
 📅  October 31st, 10:18
 🌎  https://cocoapods.org/pods/RxRealmDataSources
 👍  Tell your friends!

**Comment by icanzilb** [comment]
Thanks! Not sure what went wrong with my setup, all the ruby stuff is just 💥🤦🏽‍♂️
