### ISSUE TITLE
Usage with filters

### ISSUE THREAD

**Issue by ncioj10** [RxSwiftCommunity/RxRealmDataSources#5]
Hi,
first of all thank you for your work on this project and I really appreciate it. 
I am currently facing the integration of a Search for my TableView together with Realm and I tried this library. 
Unfortunately I did not find any possibility to filter the items except for deleting them. 
It would be very helpful, if you had any tip on how I can achieve a behaviour like that (https://realm.io/news/marin-todorov-realm-rxswift/).

Kind regards,
Nicolas

**Comment by icanzilb** [comment]
@ncioj10 a different `filter` would mean you need a different collection of objects, e.g. you will need to create a new `Results` object and bind it to your table view. `RxRealmDataSources` takes care only to display data in a table or collection view - it doesn't change the way you find or filter objects. (e.g. in the post you linked RxRealmDataSources takes care of the very last block of code under `// Table view magic`)

**Comment by ncioj10** [comment]
Thank you for the quick reply. My code now works and since it may help anyone I've posted a sample of it below (a bit anonymized). If there are any remarks on the code I'll be happy to adjust it:

`    //MARK: - View Setup
    @IBOutlet weak var searchText: UITextField!
    @IBOutlet weak var contactTypeControl: UISegmentedControl!
    @IBOutlet weak var objectsTable: UITableView!
    
    //MARK: - Properties
    let bag = DisposeBag()
    var resultsBag = DisposeBag()
    
    let realm = RealmManager.realm
    
    var objects: Results<RealmObject>?
    var dataSource: RxTableViewRealmDataSource<RealmObject>?
    
    
    override func viewDidLoad() {
        super.viewDidLoad()

        //define input
        let input = Observable.combineLatest(searchText.rx.text.orEmpty, contactTypeControl.rx.value)
        {term, type in (term, type)}
            .shareReplay(1)
        
        input.throttle(0.3, scheduler: MainScheduler.instance)
            .distinctUntilChanged{
                ($0.1 == $1.1 && $1.0 == $0.0)
            }
                .subscribe(onNext: {[weak self] (term,type) in
                self?.bindTableView(term, type: type)
        })
            .addDisposableTo(bag)
        
    }
        
    
    /// bind results to table view
    func bindTableView(_ term: String, type: Int) {
        resultsBag = DisposeBag()
        // create data source
        dataSource = RxTableViewRealmDataSource<RealmObject>(cellIdentifier: "Cell", cellType: RealmObjectCell.self) {cell, ip, contact in
            cell.name.text = "\(contact.firstName) \(contact.lastName)"
        }
        if(term.isEmpty){
            //Type 0==All, Type 1 == Registered, Type 2 = Not-registered
           let isUser = type == 1 ? true : false
            if type == 0 {
                objects = realm?.objects(RealmObject.self)
            }else{
                objects = realm?.objects(RealmObject.self).filter("isUser == %@", isUser)
            }
        }else{
            //Type 0==All, Type 1 == Registered, Type 2 = Not-registered
            if type == 0 {
                objects = realm?.objects(RealmObject.self).filter("firstName CONTAINS[c] %@ OR lastName CONTAINS[c] %@", term, term)
            }else{
                objects = realm?.objects(RealmObject.self).filter("(firstName CONTAINS[c] %@ OR lastName CONTAINS[c] %@) AND isUser == %@", term, term, isUser)
            }
        }
        
        guard objects?.count != 0 else{
            objectsTable.reloadData()
            return
        }
        
        let objectsObservable = Observable.changeset(from: objects!)
            .share()
        
        // bind to table view
       objectsObservable
            .bindTo(objectsTable.rx.realmChanges(dataSource!))
            .addDisposableTo(resultsBag)
    }`

**Comment by pluckq** [comment]
Hello, so if I go that way I would miss animated changes? And getting weird bug with scroll insets in the bottom, like there 2 empty rows
Maybe any other way to achieve this functional?

**Comment by farooq82** [comment]
Another approach could be to modify underlying realm objects and leave change set as it is. 

```
class Vacancy:Object, Mappable{
    dynamic var vacancyRefNo:String?
    dynamic var position:String?
    dynamic var isSearched = true
}
```

In search function modify `isSearched` property of realm objects to include or exclude from search. It's kind of inverse search.

```
@discardableResult
func search(realm: Realm, searchText:String?) -> Observable<Results<Vacancy>>{
        let all = realm.objects(Vacancy.self)
        
        guard let searchText = searchText, searchText.isEmpty == false else{
            try? realm.write {
                all.setValue(true, forKey: "isSearched")
            }
            return Observable.collection(from: all)
        }
        
        let filtered = all.filter("NOT (position CONTAINS[c] %@)", searchText)
        try? realm.write {
            if(all.count == filtered.count){
                filtered.setValue(false, forKey: "isSearched")
            }else{
                for vacancy in filtered{
                    vacancy.isSearched = false
                }
            }
        }
        return Observable.collection(from: filtered)
    }
```

Subscribe to search textfield to observe for text changes and perform search.

```
tfSearch.rx.text
        .observeOn(MainScheduler.instance)
            .subscribe(onNext:{text in
                search(text:text)
            })
            .addDisposableTo(this.rx_disposeBag)
```

And leave tableview bindings unchanged:

```
viewModel.loadVacancies()
            .bind(to: tableView.rx.realmChanges(dataSource))
            .addDisposableTo(rx_disposeBag)
```
