### ISSUE TITLE
Can modify the next headerTitle, footerTitle

### ISSUE THREAD

**Issue by LiuSky** [RxSwiftCommunity/RxRealmDataSources#6]
such as:
   RxRxDataSources 
<img width="774" alt="2017-03-06 2 53 38" src="https://cloud.githubusercontent.com/assets/3087745/23599554/c672328c-027c-11e7-99a9-2f6188af5d5c.png">

Thank you @icanzilb

**Comment by icanzilb** [comment]
You can set the title and footer of the table view by setting the `headerTitle` and `footerTitle` properties on the data source object. 

https://github.com/RxSwiftCommunity/RxRealmDataSources/blob/master/Pod/Classes/RxTableViewRealmDataSource.swift#L36

**Comment by LiuSky** [comment]
I'm sorry, maybe I'm not clear enough，I want headerTitle, footerTitle content is dynamic.Sometimes they are empty, sometimes they have data @icanzilb

**Comment by icanzilb** [comment]
This you can achieve by setting a delegate to the table view and implement `footerView(forSection:) ` as usual. This would work as non-rx code

**Comment by LiuSky** [comment]
I'm sorry, I'm a custom. @icanzilb
