### ISSUE TITLE
Would be great to support > sections and clicking on the cells?

### ISSUE THREAD

**Issue by jonchui** [RxSwiftCommunity/RxRealmDataSources#7]
thanks!

**Comment by icanzilb** [comment]
re: sections - yes, it would be great, certainly something to look into for future versions
re: clicking on the cells - no idea what do you mean, maybe add a more detailed explanation?

**Comment by jonchui** [comment]
re: sections, did you have any plans? or how would you plan on exposing another section?

re: cells: hooking into the tableview delegate's `didSelectRowAt` so we can handle tapping on a row?

**Comment by icanzilb** [comment]
re: clicking on cells, this seems like a task for the table's delegate, not the data source 
re: sections, no I haven't planned on this feature just yet

**Comment by retsohuang** [comment]
@jonchui If you went to handle tapping in a row, check o ut [RxCocoa](https://github.com/ReactiveX/RxSwift/tree/master/RxCocoa)

```
tableView.rx.itemSelected
```

**Comment by kingmatusevich** [comment]
This is what happens when you hook into tableView.rx.itemSelected:
```
fatal error: This method only works in case one of the `rx.items*` methods was used.: file /Users/javiermatusevich/Development/FeedSum/Carthage/Checkouts/RxSwift/RxCocoa/RxCocoa.swift, line 154
```

**Comment by icanzilb** [comment]
@jonchui @retsohuang @kingmatusevich 

the PR by @imaccallum adds cell taps to the latest release: https://github.com/RxSwiftCommunity/RxRealmDataSources/releases/tag/0.2.2

**Comment by icanzilb** [comment]
about sections - it's a difficult topic, I've been dabbing at it for a long time but realm results are inherently unsanctioned and I'm not 100% how to approach this

**Comment by jonchui** [comment]
@icanzilb is there a reason we closed this issue on multi-sections?

i feel like having multiple-sections in a table is a pretty normal use case

**Comment by icanzilb** [comment]
feel free to send a PR or otherwise contribute more to this topic

**Comment by icanzilb** [comment]
I mean, this issue just says that it would be great to support sections and I agree, but there wasn't anything valuable added to the conversation - that's why the issue is closed. if there's some code or other ideas to add - please do
