### ISSUE TITLE
Make DataSources declarations open for inheritance

### ISSUE THREAD

**Issue by epinaud** [RxSwiftCommunity/RxRealmDataSources#9]
First of all, great job on this classes. Thanks for the effort.

I would suggest to make the declaration of the main clases (`RxCollectionViewRealmDataSource` and `RxTableViewRealmDataSource`) **open** instead of **private**. It is probably good to allow users to inherit from those classes.

On the other hand, what about implementing `tableView(_ tableView: UITableView, commit editingStyle: UITableViewCellEditingStyle, forRowAt indexPath: IndexPath)` in order to provide "swipe to delete" functionality?

Regards,

**Comment by icanzilb** [comment]
yeah I think you're right, I don't want to clone all the functionality already available in `RxDataSources` so maybe making the classes `open` is the way to allow everyone to add pieces they need as they go.

**Comment by pluckq** [comment]
Bump. Would be great to get this.

**Comment by icanzilb** [comment]
@pluckq will do! do you care to make a PR for it?

**Comment by icanzilb** [comment]
addressed in `0.2.4` thanks for your patience
